
package com.yeah.webservice.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebService", targetNamespace = "http://server.soap.webservice.yeah.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://server.soap.webservice.yeah.com/", className = "com.yeah.webservice.soap.client.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://server.soap.webservice.yeah.com/", className = "com.yeah.webservice.soap.client.SaveResponse")
    @Action(input = "http://server.soap.webservice.yeah.com/MyWebService/saveRequest", output = "http://server.soap.webservice.yeah.com/MyWebService/saveResponse")
    public String save(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.soap.webservice.yeah.com/", className = "com.yeah.webservice.soap.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.soap.webservice.yeah.com/", className = "com.yeah.webservice.soap.client.SayHelloResponse")
    @Action(input = "http://server.soap.webservice.yeah.com/MyWebService/sayHelloRequest", output = "http://server.soap.webservice.yeah.com/MyWebService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
